
import { Box } from '@mui/system'
import '../../../App.css'
import { Card, CardContent } from "@mui/material"
import { useEffect } from 'react'

function PrivacyPolicy() {

    const cardStyle = {
        margin: '20px',
        padding: '20px',
        backgroundColor: 'rgba(255, 255, 255, 0.5)'
    };
    useEffect(() => {
        window.scrollTo(0, 0)
    }, [])
    return (
        <Box className='container-background' sx={{ minHeight: '1200px' }}>
            <Card sx={cardStyle}>
                <CardContent>
                    <p className='privacy-header font-montserrat-bold'>1. Introduction</p>
                    <p className="font-nunito-300 subSection-content" style={{ lineHeight: '1.5rem' }}>Welcome to www.pujaayojan.com ("we," "our," or "us"). Your privacy is important to us. This Privacy Policy is designed to help you understand how we collect, use, and protect your personal information when you use our website or services.
                        This Privacy Policy is an electronic record as per the Information Technology Act, 2000 (as amended / re-enacted) and rules thereunder ("IT Act") and is published in accordance with the provisions of Rule 3 (1) of the of the Information Technology (Intermediaries Guidelines and Digital Media Ethics code) Rules, 2021, which mandates the publishing of rules and regulations, privacy policy and terms and conditions for access or usage of any application or website. This electronic record is generated by a computer system and does not require any physical or digital signature. We request you to go through this Privacy Policy and the Terms of Use (https://www.pujaayojan.com/terms-of-use/) carefully before you decide to access this Platform and avail the Services.
                    </p>
                    <br />
                    <p className='privacy-header font-montserrat-bold'>2. Information We Collect</p>
                    <p className='privacy-header font-montserrat-bold'>2.1 Personal Information:</p>
                    <p className="font-nunito-300 subSection-content" style={{ lineHeight: '2rem' }}>Full Name Contact Information (email address, phone number, mailing address) Date of Birth, Gender, Credit Card or Debit Card Bank Account Information for payment purpose or Customer ID.</p>
                    <p className="font-nunito-300 subSection-content" style={{ lineHeight: '2rem' }}><span className='privacy-span'>2.2</span> It is clarified that in the event you make any payments through the Platform, we will not store any payment or card related information which you may provide in the course of making such payments, such as card number, account number, validity date, expiry date or CVV number.</p>
                    <br />
                    <p className='privacy-header font-montserrat-bold'>3. Collecting information for services</p>
                    <p className="font-nunito-300 subSection-content" style={{ lineHeight: '2rem' }}><span className='privacy-span'>3.1 Providing Services:</span> We use your information to provide, maintain, and enhance the services offered on our website. This includes but is not limited to account creation, order processing, and delivering content or features relevant to your needs and preferences.</p>
                    <p className="font-nunito-300 subSection-content" style={{ lineHeight: '2rem' }}><span className='privacy-span'>3.2 Communication:</span> We may use your contact information, such as your email address, to respond to your inquiries, provide customer support, and deliver important updates related to our services.</p>
                    <p className="font-nunito-300 subSection-content" style={{ lineHeight: '2rem' }}><span className='privacy-span'>3.3 Legal and Security:</span> Your information may be used to protect our legal rights and address security issues. We take the security of your data seriously and employ measures to ensure its protection.</p>
                    <p className="font-nunito-300 subSection-content" style={{ lineHeight: '2rem' }}>By using our services and providing your information, you consent to these practices. We are committed to safeguarding your data and using it exclusively for the purposes described in this privacy policy.</p>
                    <br />
                    <p className='privacy-header font-montserrat-bold'>4. Sharing the Information</p>
                    <p className="font-nunito-300 subSection-content" style={{ lineHeight: '2rem' }}><span className='privacy-span'>4.1 Service Providers, Partners, and Affiliates:</span> We may share customer information with trusted service providers, business partners, and affiliates who assist us in delivering our services. These entities are contractually bound to handle your data securely and in accordance with our privacy policy.</p>
                    <p className="font-nunito-300 subSection-content" style={{ lineHeight: '2rem' }}><span className='privacy-span'>4.2 Legal and Regulatory Requirements:</span> We may disclose your information to comply with legal obligations, regulatory agencies, or in response to court orders, subpoenas, or other legal processes. This includes situations where we believe disclosure is necessary to protect our legal rights, prevent fraud, or address security issues.</p>
                    <p className="font-nunito-300 subSection-content" style={{ lineHeight: '2rem' }}><span className='privacy-span'>4.3 Business Transactions:</span> In the event of a merger, acquisition, or sale of assets, customer information may be transferred to the acquiring entity. We will ensure that your data continues to be treated in compliance with our privacy policy.</p>
                    <p className="font-nunito-300 subSection-content" style={{ lineHeight: '2rem' }}>Your privacy is important to us, and we are committed to sharing your information responsibly and in accordance with applicable privacy laws and regulations.</p>
                    <br />
                    <p className='privacy-header font-montserrat-bold'>5. Cookies</p>
                    <p className="font-nunito-300 subSection-content" style={{ lineHeight: '2rem' }}>Cookies are small text files that are stored on your device when you visit our website. They help us recognize your device, remember your preferences, and improve your experience.</p>
                    <p className="font-nunito-300 subSection-content" style={{ lineHeight: '2rem' }}><span className='privacy-span'>5.1</span> These cookies are necessary for the website to function correctly, such as maintaining your session and enabling basic functions.</p>
                    <p className="font-nunito-300 subSection-content" style={{ lineHeight: '2rem' }}><span className='privacy-span'>5.2</span> These cookies help us understand how visitors use our website, allowing us to improve functionality and performance.</p>
                    <p className="font-nunito-300 subSection-content" style={{ lineHeight: '2rem' }}><span className='privacy-span'>5.3</span> These cookies remember your preferences, such as language settings or location, to enhance your experience.</p>
                    <p className="font-nunito-300 subSection-content" style={{ lineHeight: '2rem' }}><span className='privacy-span'>5.4</span> These cookies are used to deliver relevant advertisements based on your interests.</p>
                    <p className="font-nunito-300 subSection-content" style={{ lineHeight: '2rem' }}><span className='privacy-span'>5.5</span> By using our website, you consent to the use of cookies as described in this privacy policy. You can manage your cookie preferences through your browser settings.</p>
                    <p className="font-nunito-300 subSection-content" style={{ lineHeight: '2rem' }}>We may allow third-party service providers to set cookies on our website to perform various functions, such as analytics or advertising. These third parties have their own privacy policies and may collect and use your data independently.</p>
                    <p className="font-nunito-300 subSection-content" style={{ lineHeight: '2rem' }}>You can control and manage cookie preferences through your browser settings. You may also opt out of specific types of cookies, such as advertising cookies, through industry opt-out tools or your device settings.</p>
                    <p className="font-nunito-300 subSection-content" style={{ lineHeight: '2rem' }}>We take data protection and privacy seriously. Information collected via cookies is subject to our privacy policy and is used in accordance with applicable data protection laws.</p>
                    <p className="font-nunito-300 subSection-content" style={{ lineHeight: '2rem' }}>Please be aware that disabling or blocking certain cookies may affect the functionality and performance of our website. For more information about our cookie practices or to manage your preferences, please refer to our Cookie Policy.</p>
                    <br />
                    <p className='privacy-header font-montserrat-bold'>6. Security Procedures</p>
                    <p className="font-nunito-300 subSection-content" style={{ lineHeight: '2rem' }}>We have implemented rigorous technical and organizational measures to protect your information from unauthorized access, disclosure, alteration, or destruction. These measures include encryption, access controls, and regular security assessments.</p>
                    <p className="font-nunito-300 subSection-content" style={{ lineHeight: '2rem' }}>While we take every precaution to protect your data, it's important to recognize that no system is entirely immune to security risks. By using our services, you acknowledge and accept these inherent risks. We recommend that you also take steps to protect your data, such as using strong, unique passwords and keeping your login credentials secure.</p>
                    <p className="font-nunito-300 subSection-content" style={{ lineHeight: '2rem' }}>We are committed to continually enhancing our security procedures and ensuring the privacy and protection of your information.</p>
                    <br />
                    <p className='privacy-header font-montserrat-bold'>7. Privacy Policy Disclaimer</p>
                    <p className="font-nunito-300 subSection-content" style={{ lineHeight: '2rem' }}>www.pujaayojan.com is committed to protecting your privacy. This Privacy Policy Disclaimer explains our practices regarding the collection, use, and sharing of your personal information. By using our website or services, you consent to the practices described in this Privacy Policy Disclaimer.</p>
                    <br />
                    <p className='privacy-header font-montserrat-bold'>Contact Us</p>
                    <p className="font-nunito-300" style={{ lineHeight: '2rem' }}>If you have any questions or concerns about this Privacy Policy Disclaimer or your personal information, please contact us at namaste@pujaayojan.com</p>
                </CardContent>
            </Card>
        </Box>
    )
}

export default PrivacyPolicy